// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Account struct {
	ID        uint      `json:"id"`
	Owner     string    `json:"owner" binding:"required"`
	Balance   int64     `json:"balance" binding:"required"`
	Currency  string    `json:"currency" binding:"required,oneof=USD EUR"`
}
type GetAccountRequest struct {
	ID 		uint		`uri:"id" binging:"required,min=1"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be positive/negative
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
